services:
  db:
    ports:
      - "5432:5432"

  app:
    ports:
      - "8080:8080"

  memcached:
    ports:
    - "11211:11211"

  jaeger:
    ports:
      - "16686:16686"
      - "14268:14268"

  nats:
    ports:
      - "8222:8222"