# Dockerfile.dev
FROM golang:1.25-alpine AS builder

# Устанавливаем air и curl (для healthcheck, если нужен)
RUN go install github.com/air-verse/air@latest && \
    apk add --no-cache curl

WORKDIR /app

# Копируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники (будут переопределены volume'ом при запуске)
COPY . .

# Запускаем air
CMD ["air", "-c", ".air.toml"]