// Code generated by MockGen. DO NOT EDIT.
// Source: astro_interface.go
//
// Generated by this command:
//
//	mockgen -source=astro_interface.go -destination=mocks/mock_astro_interface.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	astroprocapi "astroapi/internal/astroproc"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAstroProc is a mock of AstroProc interface.
type MockAstroProc struct {
	ctrl     *gomock.Controller
	recorder *MockAstroProcMockRecorder
	isgomock struct{}
}

// MockAstroProcMockRecorder is the mock recorder for MockAstroProc.
type MockAstroProcMockRecorder struct {
	mock *MockAstroProc
}

// NewMockAstroProc creates a new mock instance.
func NewMockAstroProc(ctrl *gomock.Controller) *MockAstroProc {
	mock := &MockAstroProc{ctrl: ctrl}
	mock.recorder = &MockAstroProcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAstroProc) EXPECT() *MockAstroProcMockRecorder {
	return m.recorder
}

// GetAstroProfile mocks base method.
func (m *MockAstroProc) GetAstroProfile(ctx context.Context, userID string) (astroprocapi.AstroProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAstroProfile", ctx, userID)
	ret0, _ := ret[0].(astroprocapi.AstroProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAstroProfile indicates an expected call of GetAstroProfile.
func (mr *MockAstroProcMockRecorder) GetAstroProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAstroProfile", reflect.TypeOf((*MockAstroProc)(nil).GetAstroProfile), ctx, userID)
}
