// Code generated by MockGen. DO NOT EDIT.
// Source: astroapi/internal/repositories (interfaces: PersonalDataRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_personal_data_repo.go -package=mocks . PersonalDataRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "astroapi/internal/repositories/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPersonalDataRepository is a mock of PersonalDataRepository interface.
type MockPersonalDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalDataRepositoryMockRecorder
	isgomock struct{}
}

// MockPersonalDataRepositoryMockRecorder is the mock recorder for MockPersonalDataRepository.
type MockPersonalDataRepositoryMockRecorder struct {
	mock *MockPersonalDataRepository
}

// NewMockPersonalDataRepository creates a new mock instance.
func NewMockPersonalDataRepository(ctrl *gomock.Controller) *MockPersonalDataRepository {
	mock := &MockPersonalDataRepository{ctrl: ctrl}
	mock.recorder = &MockPersonalDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalDataRepository) EXPECT() *MockPersonalDataRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockPersonalDataRepository) Save(ctx context.Context, data domain.PersonalData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPersonalDataRepositoryMockRecorder) Save(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPersonalDataRepository)(nil).Save), ctx, data)
}
