global:
  scrape_interval: 360s
  evaluation_interval: 360s

scrape_configs:
  - job_name: "astrostilist_backend"
    static_configs:
      - targets: [ "app:8080" ]
    metrics_path: "/metrics"

rule_files:
  - "alerts/*.yaml"