// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mocks/mock_crmcliente.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "astroapi/internal/repositories/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCrmClient is a mock of CrmClient interface.
type MockCrmClient struct {
	ctrl     *gomock.Controller
	recorder *MockCrmClientMockRecorder
	isgomock struct{}
}

// MockCrmClientMockRecorder is the mock recorder for MockCrmClient.
type MockCrmClientMockRecorder struct {
	mock *MockCrmClient
}

// NewMockCrmClient creates a new mock instance.
func NewMockCrmClient(ctrl *gomock.Controller) *MockCrmClient {
	mock := &MockCrmClient{ctrl: ctrl}
	mock.recorder = &MockCrmClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCrmClient) EXPECT() *MockCrmClientMockRecorder {
	return m.recorder
}

// SendProfile mocks base method.
func (m *MockCrmClient) SendProfile(ctx context.Context, profile domain.AstroProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendProfile indicates an expected call of SendProfile.
func (mr *MockCrmClientMockRecorder) SendProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendProfile", reflect.TypeOf((*MockCrmClient)(nil).SendProfile), ctx, profile)
}

// SendRecommend mocks base method.
func (m *MockCrmClient) SendRecommend(ctx context.Context, recommend string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendRecommend", ctx, recommend)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendRecommend indicates an expected call of SendRecommend.
func (mr *MockCrmClientMockRecorder) SendRecommend(ctx, recommend any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendRecommend", reflect.TypeOf((*MockCrmClient)(nil).SendRecommend), ctx, recommend)
}
