port: 4222
http_port: 8222
system_account: SYS

# Logging
debug: false
trace: false
logtime: true

# JetStream configuration
jetstream {
    store_dir: /data/jetstream
    max_mem: 1G
    max_file: 10G
}

accounts: {
    APP: {
        users: [
            { user: app, password: app }
        ],
        jetstream: {
            max_mem: 1G
            max_file: 10G
        }
    },
    SYS: {
        users: [
            { user: sys, password: sys }
        ]
    }
}

no_auth_user: app