// Code generated by MockGen. DO NOT EDIT.
// Source: astro_profile.go
//
// Generated by this command:
//
//	mockgen -source=astro_profile.go -destination=mocks/mock_astro_profile.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "astroapi/internal/repositories/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProcessAstroProfileInterface is a mock of ProcessAstroProfileInterface interface.
type MockProcessAstroProfileInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessAstroProfileInterfaceMockRecorder
	isgomock struct{}
}

// MockProcessAstroProfileInterfaceMockRecorder is the mock recorder for MockProcessAstroProfileInterface.
type MockProcessAstroProfileInterfaceMockRecorder struct {
	mock *MockProcessAstroProfileInterface
}

// NewMockProcessAstroProfileInterface creates a new mock instance.
func NewMockProcessAstroProfileInterface(ctrl *gomock.Controller) *MockProcessAstroProfileInterface {
	mock := &MockProcessAstroProfileInterface{ctrl: ctrl}
	mock.recorder = &MockProcessAstroProfileInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessAstroProfileInterface) EXPECT() *MockProcessAstroProfileInterfaceMockRecorder {
	return m.recorder
}

// ExecuteReceivingByHash mocks base method.
func (m *MockProcessAstroProfileInterface) ExecuteReceivingByHash(ctx context.Context, hash string) (*domain.AstroProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteReceivingByHash", ctx, hash)
	ret0, _ := ret[0].(*domain.AstroProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteReceivingByHash indicates an expected call of ExecuteReceivingByHash.
func (mr *MockProcessAstroProfileInterfaceMockRecorder) ExecuteReceivingByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteReceivingByHash", reflect.TypeOf((*MockProcessAstroProfileInterface)(nil).ExecuteReceivingByHash), ctx, hash)
}

// ExecuteSave mocks base method.
func (m *MockProcessAstroProfileInterface) ExecuteSave(ctx context.Context, profile domain.AstroProfile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteSave", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteSave indicates an expected call of ExecuteSave.
func (mr *MockProcessAstroProfileInterfaceMockRecorder) ExecuteSave(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteSave", reflect.TypeOf((*MockProcessAstroProfileInterface)(nil).ExecuteSave), ctx, profile)
}
