// Code generated by MockGen. DO NOT EDIT.
// Source: products.go
//
// Generated by this command:
//
//	mockgen -source=products.go -destination=mocks/mock_products.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "astroapi/internal/models"
	products "astroapi/internal/products"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheInvalidator is a mock of CacheInvalidator interface.
type MockCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockCacheInvalidatorMockRecorder is the mock recorder for MockCacheInvalidator.
type MockCacheInvalidatorMockRecorder struct {
	mock *MockCacheInvalidator
}

// NewMockCacheInvalidator creates a new mock instance.
func NewMockCacheInvalidator(ctrl *gomock.Controller) *MockCacheInvalidator {
	mock := &MockCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheInvalidator) EXPECT() *MockCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateProduct mocks base method.
func (m *MockCacheInvalidator) InvalidateProduct(ctx context.Context, sku string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateProduct", ctx, sku)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateProduct indicates an expected call of InvalidateProduct.
func (mr *MockCacheInvalidatorMockRecorder) InvalidateProduct(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateProduct", reflect.TypeOf((*MockCacheInvalidator)(nil).InvalidateProduct), ctx, sku)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetBySKU mocks base method.
func (m *MockRepository) GetBySKU(ctx context.Context, sku string) (models.CatalogProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySKU", ctx, sku)
	ret0, _ := ret[0].(models.CatalogProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySKU indicates an expected call of GetBySKU.
func (mr *MockRepositoryMockRecorder) GetBySKU(ctx, sku any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySKU", reflect.TypeOf((*MockRepository)(nil).GetBySKU), ctx, sku)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, options products.ListOptions) (products.ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, options)
	ret0, _ := ret[0].(products.ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, options)
}

// Patch mocks base method.
func (m *MockRepository) Patch(ctx context.Context, sku string, input products.PatchInput) (models.CatalogProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, sku, input)
	ret0, _ := ret[0].(models.CatalogProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockRepositoryMockRecorder) Patch(ctx, sku, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockRepository)(nil).Patch), ctx, sku, input)
}

// Recommend mocks base method.
func (m *MockRepository) Recommend(ctx context.Context, tags []string, gender, scenario string, preferences map[string]any) ([]models.CatalogProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recommend", ctx, tags, gender, scenario, preferences)
	ret0, _ := ret[0].([]models.CatalogProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recommend indicates an expected call of Recommend.
func (mr *MockRepositoryMockRecorder) Recommend(ctx, tags, gender, scenario, preferences any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recommend", reflect.TypeOf((*MockRepository)(nil).Recommend), ctx, tags, gender, scenario, preferences)
}
