// Code generated by MockGen. DO NOT EDIT.
// Source: message.go
//
// Generated by this command:
//
//	mockgen -source=message.go -destination=mocks/mock_message.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "astroapi/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventHandler is a mock of EventHandler interface.
type MockEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockEventHandlerMockRecorder
	isgomock struct{}
}

// MockEventHandlerMockRecorder is the mock recorder for MockEventHandler.
type MockEventHandlerMockRecorder struct {
	mock *MockEventHandler
}

// NewMockEventHandler creates a new mock instance.
func NewMockEventHandler(ctrl *gomock.Controller) *MockEventHandler {
	mock := &MockEventHandler{ctrl: ctrl}
	mock.recorder = &MockEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventHandler) EXPECT() *MockEventHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockEventHandler) Handle(ctx context.Context, payload []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockEventHandlerMockRecorder) Handle(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockEventHandler)(nil).Handle), ctx, payload)
}

// MockMsgPublisher is a mock of MsgPublisher interface.
type MockMsgPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMsgPublisherMockRecorder
	isgomock struct{}
}

// MockMsgPublisherMockRecorder is the mock recorder for MockMsgPublisher.
type MockMsgPublisherMockRecorder struct {
	mock *MockMsgPublisher
}

// NewMockMsgPublisher creates a new mock instance.
func NewMockMsgPublisher(ctrl *gomock.Controller) *MockMsgPublisher {
	mock := &MockMsgPublisher{ctrl: ctrl}
	mock.recorder = &MockMsgPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMsgPublisher) EXPECT() *MockMsgPublisherMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockMsgPublisher) PublishMessage(ctx context.Context, streamName, subject string, payload any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", ctx, streamName, subject, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockMsgPublisherMockRecorder) PublishMessage(ctx, streamName, subject, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockMsgPublisher)(nil).PublishMessage), ctx, streamName, subject, payload)
}

// MockMsgDLQReader is a mock of MsgDLQReader interface.
type MockMsgDLQReader struct {
	ctrl     *gomock.Controller
	recorder *MockMsgDLQReaderMockRecorder
	isgomock struct{}
}

// MockMsgDLQReaderMockRecorder is the mock recorder for MockMsgDLQReader.
type MockMsgDLQReaderMockRecorder struct {
	mock *MockMsgDLQReader
}

// NewMockMsgDLQReader creates a new mock instance.
func NewMockMsgDLQReader(ctrl *gomock.Controller) *MockMsgDLQReader {
	mock := &MockMsgDLQReader{ctrl: ctrl}
	mock.recorder = &MockMsgDLQReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMsgDLQReader) EXPECT() *MockMsgDLQReaderMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockMsgDLQReader) GetMessages(ctx context.Context) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockMsgDLQReaderMockRecorder) GetMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockMsgDLQReader)(nil).GetMessages), ctx)
}
