// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handlers/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handlers/handler.go -destination=internal/handlers/mocks/mock_hello.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHelloService is a mock of HelloService interface.
type MockHelloService struct {
	ctrl     *gomock.Controller
	recorder *MockHelloServiceMockRecorder
	isgomock struct{}
}

// MockHelloServiceMockRecorder is the mock recorder for MockHelloService.
type MockHelloServiceMockRecorder struct {
	mock *MockHelloService
}

// NewMockHelloService creates a new mock instance.
func NewMockHelloService(ctrl *gomock.Controller) *MockHelloService {
	mock := &MockHelloService{ctrl: ctrl}
	mock.recorder = &MockHelloServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelloService) EXPECT() *MockHelloServiceMockRecorder {
	return m.recorder
}

// GetDBStatus mocks base method.
func (m *MockHelloService) GetDBStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDBStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDBStatus indicates an expected call of GetDBStatus.
func (mr *MockHelloServiceMockRecorder) GetDBStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDBStatus", reflect.TypeOf((*MockHelloService)(nil).GetDBStatus))
}
