// Code generated by MockGen. DO NOT EDIT.
// Source: processors.go

// Package mocks is a generated GoMock package.
package mocks

import (
	astro "astroapi/internal/astro"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAstroProvider is a mock of AstroProvider interface.
type MockAstroProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAstroProviderMockRecorder
	isgomock struct{}
}

// MockAstroProviderMockRecorder is the mock recorder for MockAstroProvider.
type MockAstroProviderMockRecorder struct {
	mock *MockAstroProvider
}

// NewMockAstroProvider creates a new mock instance.
func NewMockAstroProvider(ctrl *gomock.Controller) *MockAstroProvider {
	mock := &MockAstroProvider{ctrl: ctrl}
	mock.recorder = &MockAstroProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAstroProvider) EXPECT() *MockAstroProviderMockRecorder {
	return m.recorder
}

// GetNatalChart mocks base method.
func (m *MockAstroProvider) GetNatalChart(ctx context.Context, dob astro.DateOfBirth, lat, lon float64) (astro.NatalData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNatalChart", ctx, dob, lat, lon)
	ret0, _ := ret[0].(astro.NatalData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNatalChart indicates an expected call of GetNatalChart.
func (mr *MockAstroProviderMockRecorder) GetNatalChart(ctx, dob, lat, lon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNatalChart", reflect.TypeOf((*MockAstroProvider)(nil).GetNatalChart), ctx, dob, lat, lon)
}
