// Code generated by MockGen. DO NOT EDIT.
// Source: processors.go
//
// Generated by this command:
//
//	mockgen -source=processors.go -destination=mocks/mock_processors.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	alisa "astroapi/internal/alisa"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAstroProfileGetter is a mock of AstroProfileGetter interface.
type MockAstroProfileGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAstroProfileGetterMockRecorder
	isgomock struct{}
}

// MockAstroProfileGetterMockRecorder is the mock recorder for MockAstroProfileGetter.
type MockAstroProfileGetterMockRecorder struct {
	mock *MockAstroProfileGetter
}

// NewMockAstroProfileGetter creates a new mock instance.
func NewMockAstroProfileGetter(ctrl *gomock.Controller) *MockAstroProfileGetter {
	mock := &MockAstroProfileGetter{ctrl: ctrl}
	mock.recorder = &MockAstroProfileGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAstroProfileGetter) EXPECT() *MockAstroProfileGetterMockRecorder {
	return m.recorder
}

// GetAstroProfileContext mocks base method.
func (m *MockAstroProfileGetter) GetAstroProfileContext(ctx context.Context, birthDate, birthPlace string) (alisa.AstroProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAstroProfileContext", ctx, birthDate, birthPlace)
	ret0, _ := ret[0].(alisa.AstroProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAstroProfileContext indicates an expected call of GetAstroProfileContext.
func (mr *MockAstroProfileGetterMockRecorder) GetAstroProfileContext(ctx, birthDate, birthPlace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAstroProfileContext", reflect.TypeOf((*MockAstroProfileGetter)(nil).GetAstroProfileContext), ctx, birthDate, birthPlace)
}
